#!/bin/bash

# ================================================================
# This is the file which will be sourced on the away host to set up aliases.
# You must
#
#   . /path/to/this/file
#
# (note the '.') in order to have effect on the calling shell's PATH variable.
#
# ================================================================
# John Kerl 2021-08-08
# ================================================================

ourdir=$HOME/away

export PATH=$ourdir/bin-general:$PATH
export PATH=$ourdir/bin-project:$PATH
export PATH=.:$PATH
ln -f -s /usr/local/bin/python3 python

. $ourdir/bashrc-general
. $ourdir/bashrc-project
if [ -f $ourdir/project-aliases ]; then
  . $ourdir/project-aliases
fi
cdt=$HOME/git/TileDB-Inc/cloud-dev-temp
if [ -f $cdt/vars-site-shared ]; then
  . $cdt/vars-site-shared
fi
if [ -d $cdt ]; then
  export PATH=$cdt:$PATH
  export PATH=$cdt/scripts:$PATH
fi

bind '"\C-w": backward-kill-word'
alias vim='vim -u $ourdir/vimrc'
